import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'
import type { ReactNode } from 'react'
import './globals.css'

export const metadata: Metadata = {
  title: 'Proactime',
  description: 'Generated by create next app'
}

const poppins = Poppins({ subsets: ['latin'], weight: ['400', '600', '700'] })

export default function RootLayout({
  children
}: Readonly<{ children: ReactNode }>) {
  return (
    <html lang='en'>
      <body className={`antialiased ${poppins.className}`}>{children}</body>
    </html>
  )
}
